version: '3.8'

services:
  laravel-app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile
    image: laravel-app:latest
    ports:
      - "8000:80"
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - mysql
      - redis
    env_file:
      - .env.docker
    networks:
      - app-network

  recommender-service:
    build:
      context: ./recommender-service
      dockerfile: Dockerfile
    image: recommender-service:latest
    ports:
      - "8001:8000"
    volumes:
      - ./recommender-service:/app
    depends_on:
      - mysql
      - redis
    env_file:
      - .env.docker
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
